### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by lawy623** [roxanneluo/Consistent-Video-Depth-Estimation#1]
Hi,

Great to see the awesome work! May I ask when will the code be released? I heard Johannes said it should be released very soon~

**Comment by patrick-llgc** [comment]
Looking forward to the code release!

**Comment by 143396** [comment]
Also looking forward to the code release!

**Comment by arturojreal** [comment]
+1!

**Comment by Luiz-Monad** [comment]
Can we at least have some Matlab workbooks?

**Comment by brstar96** [comment]
me too! :)

**Comment by dr-benway** [comment]
+1

**Comment by b29b** [comment]
+1

**Comment by leekunhee** [comment]
🙈+1

**Comment by 143396** [comment]
The code is here!!!!! https://github.com/facebookresearch/consistent_depth

**Comment by arturojreal** [comment]
> The code is here!!!!! https://github.com/facebookresearch/consistent_depth

Whoooo!
